[project]
name = "apf0703"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "av>=15.0.0",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "open3d>=0.19.0",
    "opencv-python>=4.12.0.88",
    "pandas>=2.3.1",
    "pyaudio>=0.2.14",
    "pynput>=1.8.1",
    "requests>=2.32.4",
]
